// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw6z7BwILn9n47WA4ggwb001QZDpf6vLw',
    appId: '1:1054529684370:android:d3ac15c990401cae59f74b',
    messagingSenderId: '1054529684370',
    projectId: 'vider-8cd24',
    authDomain: 'vider-8cd24.firebaseapp.com',
    storageBucket: 'vider-8cd24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw6z7BwILn9n47WA4ggwb001QZDpf6vLw',
    appId: '1:1054529684370:android:d3ac15c990401cae59f74b',
    messagingSenderId: '1054529684370',
    projectId: 'vider-8cd24',
    storageBucket: 'vider-8cd24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw6z7BwILn9n47WA4ggwb001QZDpf6vLw',
    appId: '1:1054529684370:android:d3ac15c990401cae59f74b',
    messagingSenderId: '1054529684370',
    projectId: 'vider-8cd24',
    storageBucket: 'vider-8cd24.appspot.com',
    iosBundleId: 'com.example.vider_seller',
  );
}
